name: test actions
on: [push]
jobs:

  semgrep-full:
      runs-on: ubuntu-latest
      container:
        image: returntocorp/semgrep

      steps:

        # step 1
        - name: clone application source code
          uses: actions/checkout@v3

        # step 2
        - name: full scan
          run: |
            semgrep \
              --config="p/default" \
              --json --output semgrep-results.json

        - name: send to inb4
          run: |
            curl -X POST -H "client_id: joes_client_id" \
            -H "Content-Type: application/json" \
            -H "connection_name: semgrep-sast" \
            -H "service_name: test-service" \
            -d "@semgrep-results.json" \
            https://5290-2a02-c7c-bf5d-2600-187f-a2c-f3e2-8083.ngrok-free.app/vulnerabilities

        - name: Run Snyk to check for vulnerabilities
          uses: snyk/actions/node@master
          env:
            SNYK_TOKEN: ${{ secrets.SNYK_CI }}