name: test actions
on: [push]
jobs:
  test-job:
    runs-on: ubuntu-latest
    container:
      # A Docker image with Semgrep installed. Do not change this.
      image: returntocorp/semgrep
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    