name: test actions
on: [push]
jobs:

  semgrep-full:
      runs-on: ubuntu-latest
      container:
        image: returntocorp/semgrep

      steps:

        # step 1
        - name: clone application source code
          uses: actions/checkout@v3

        # step 2
        - name: full scan
          run: |
            semgrep \
              --config="p/default" \
              --json --output semgrep-results.json

        - name: send to inb4
          run: |
            curl -X POST -H "client_id: 53270aca-80e2-42c3-994c-0fea8fac760a" \
            -H "Content-Type: application/json" \
            -H "connection_name: semgrep-sast" \
            -H "service_name: core-api" \
            -H "X-Api-Token:bd3cf2ae7e4861a7f3ea16839bbc65e4833dfa66ff519bcad1ba6a31f9bc206b"
            -d "@semgrep-results.json" \
            https://dashboard.ctrlsec.io/vulnerabilities

        - name: Run Snyk to check for vulnerabilities
          uses: snyk/actions/node@master
          env:
            SNYK_TOKEN: ${{ secrets.SNYK_CI }}