name: test actions
on: [push]
jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Semgrep
      uses: returntocorp/setup-semgrep@v1

    - name: Run Semgrep
      run: semgrep --config=p/r2c.yaml