name: test actions
on: [push]
jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Semgrep
      run: |
        curl --fail -LsSf https://semgrep.dev/install.sh | sh -s -- -b $HOME/bin
        echo "$HOME/bin" >> $GITHUB_PATH
      env:
        PATH: ${{ runner.workspace }}/.bin:$PATH

    - name: Run Semgrep
      run: semgrep --config=p/r2c.yaml