name: test actions
on: [push]
jobs:

  semgrep-full:
      runs-on: ubuntu-latest
      container:
        image: returntocorp/semgrep

      steps:

        # step 1
        - name: clone application source code
          uses: actions/checkout@v3

        # step 2
        - name: full scan
          run: |
            semgrep \
              --config="p/default" \
              --json --output results.json

        - name: send to inb4
          run: |
            curl -X POST -H "client_id: joes_client_id" \
            -H "Content-Type: application/json" \
            -H "connection_name: semgrep-sast" \
            -H "service_name: test-service" \
            -d "@results.json" \
            https://fb74-2a02-c7c-bea7-8600-531-dd55-eef9-4b8b.ngrok-free.app/vulnerabilities